export * from "./chat";
export * from "./comment";
export * from "./discipline";
export * from "./group";
export * from "./institute";
export * from "./material";
export * from "./message";
export * from "./timetable";
export * from "./user";
