export * from "./TimetablePatcher";
export * from "./UserPatcher";
export * from "./ChatPatcher";
export * from "./CommentPatcher";
export * from "./DisciplinePatcher";
export * from "./GroupPatcher";
export * from "./InstitutePatcher";
export * from "./MaterialPatcher";
export * from "./MessagePatcher";
